### ISSUE TITLE
Error on start up adminweb container after local deployment steps

### ISSUE THREAD

**Issue by AntonF-ADAC** [Azure-Samples/chat-with-your-data-solution-accelerator#1398]
# Describe the bug
After successfull deployment of the latest code with the local deployment manual trying to launch the adminweb web app to upload some custom files i get an error message:
:( Application Error (see screenshot)

# Expected behavior
The adminweb should start and load.

# How does this bug make you feel?
:(

---

# Debugging information

## Steps to reproduce
Follow the instruction for local deployment with ending in "azd up" command.

## Screenshots
![image](https://github.com/user-attachments/assets/0f50c99e-f63f-4b3f-ac91-7747d74ea460)

## Logs

In the log stream of the deployed web app this log line occures:
2024-10-09T14:56:57.547442854Z /opt/python/3/bin/python: No module named streamlit

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by devndive** [comment]
It looks like the issue was introduced with the [commit 396311](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/commit/3963114c7bf0ce9d45c37fd9b6620d40586f264b).

If you need a short term work around, you could change the services definition for adminweb and function as follows

azure.yaml
```yaml
  adminweb:
    project: ./code/backend
    language: py
    host: appservice
    hooks:
      prepackage:
        windows:
          shell: pwsh
          run: poetry install; poetry export -o requirements.txt
        posix:
          shell: sh
          run: poetry install; poetry export -o requirements.txt

  function:
    project: ./code/backend/batch
    language: py
    host: function
    hooks:
      prepackage:
        windows:
          shell: pwsh
          run: poetry export -o requirements.txt; pip install -r requirements.txt
        posix:
          shell: sh
          run: poetry export -o requirements.txt; pip install -r requirements.txt
```
