### ISSUE TITLE
Cache Poetry dependencies in `tests.yml`

### ISSUE THREAD

**Issue by cecheta** [Azure-Samples/chat-with-your-data-solution-accelerator#627]
# Motivation

Implement caching of dependencies from Poetry, as in the docs: https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages

```yaml
steps:
- uses: actions/checkout@v4
- name: Install poetry
  run: pipx install poetry
- uses: actions/setup-python@v5
  with:
    python-version: '3.9'
    cache: 'poetry'
```

# Requirements

A list of requirements to consider this feature delivered
- Add caching of Poetry dependencies

# Tasks

_To be filled in by the engineer picking up the issue_
